name: CI - Projeto Integrador 3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install --legacy-peer-deps

    - name: Build Frontend
      run: |
        cd frontend
        npm run build